baseURL = 'http://karsix.io/'
languageCode = 'en-us'
title = 'karsix'
theme = "LoveIt"

# Allow HTML in md files
[markup.goldmark.renderer]
  unsafe = true

# Author config
[author]
  name = "Kyle Rodrigues"
  email = ""
  link = ""

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "questlist"
    pre = ""
    post = ""
    name = "Quest List"
    url = "/questlist/"
    title = "Quest List"
  [[menu.main]]
    weight = 2
    identifier = "Recipes"
    pre = ""
    post = ""
    name = "Recipes"
    url = "/recipes/"
    title = "Recipes"
  [[menu.main]]
    weight = 3
    identifier = "aboutme"
    pre = ""
    post = ""
    name = "About Me"
    url = "/aboutme/"
    title = "About Me"
    
[params]
  defaultTheme = "dark"
  dateFormat = "2006-01-02"

  # Header config
  [params.header]
    [params.header.title]
      # title name
      name = "karsix"

    # Home page config
    [params.home]
        rss = 10

        [params.home.profile]
        enable = true
        # URL of avatar shown in home page
        avatarURL = "/images/avatar.jpg"
        title = "karsix"
        # subtitle shown in home page (HTML format is supported)
        subtitle = "Developer | Adventurer | Novice Home Cook"
        typeit = true
        social = true

        # Home page posts, need to keep enable to true otherwise content is offset
        [params.home.posts]
        enable = true

    # Social config about the author
    [params.social]
        GitHub = "kylerodrigues18"
        Linkedin = "kylerodrigues18"

  # Footer config
  [params.footer]
    enable = true
    hugo = false
    copyright = false
    author = false
    since = 2023